import type { AirportVehicleDTO, BikeDTO, TourDTO, VehicleRoutePrice } from "@/types";

const ROUTE_DURATIONS: Record<string, string> = {
  Weligama: "2.5–3 hrs",
  Galle: "2–2.5 hrs",
  Kandy: "3–4 hrs",
  Ella: "5–6 hrs",
  Colombo: "45–70 min",
};

function demoRoutes(prices: Record<string, number>): VehicleRoutePrice[] {
  return Object.entries(prices).map(([destination, priceUSD]) => ({
    destination,
    duration: ROUTE_DURATIONS[destination],
    priceUSD,
  }));
}

export const demoTours: TourDTO[] = [
  {
    id: "demo-cultural-triangle",
    title: "Ceylon Cultural Triangle",
    slug: "ceylon-cultural-triangle",
    location: "Sigiriya · Dambulla · Kandy",
    durationDays: 5,
    priceFrom: 620,
    image: "https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Ancient kingdoms, cave temples, village flavours and sunrise views across the heart of Sri Lanka.",
    description:
      "Follow the story of Sri Lanka through its ancient capitals, sacred temples and living village traditions. This private journey balances meaningful cultural encounters with comfortable travel and flexible stops.",
    highlights: [
      "Climb Sigiriya Rock Fortress",
      "Traditional village lunch",
      "Dambulla cave temple",
      "Kandy cultural performance",
    ],
    inclusions: ["Private air-conditioned transport", "English-speaking driver", "Daily breakfast", "Airport pickup"],
    exclusions: ["International flights", "Entrance tickets", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Airport to Sigiriya", description: "Welcome at Bandaranaike International Airport and scenic transfer to the cultural triangle." },
      { day: 2, title: "Sigiriya & Village Life", description: "Sunrise rock climb, village walk, local cooking and a relaxed afternoon." },
      { day: 3, title: "Dambulla to Kandy", description: "Visit the cave temple, spice gardens and continue through the hills to Kandy." },
      { day: 4, title: "Sacred Kandy", description: "Temple of the Tooth, botanical gardens and a traditional cultural performance." },
      { day: 5, title: "Departure", description: "Flexible transfer to Colombo, the airport or your next destination." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
  {
    id: "demo-coast",
    title: "Southern Coast & Safari",
    slug: "southern-coast-and-safari",
    location: "Galle · Mirissa · Yala",
    durationDays: 6,
    priceFrom: 740,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Fort walls, golden beaches, ocean adventures and a private wildlife safari through the island's south.",
    description:
      "Experience the easy rhythm of Sri Lanka's south coast before heading inland for a wildlife safari. The route includes heritage, local food, beach time and optional whale watching.",
    highlights: ["Galle Fort sunset", "Mirissa beach stay", "Yala jeep safari", "Stilt fishing coast"],
    inclusions: ["Private transport", "Driver-guide", "Breakfast", "Safari jeep"],
    exclusions: ["Park tickets", "Whale watching ticket", "Lunch and dinner"],
    itinerary: [
      { day: 1, title: "Airport to Galle", description: "Coastal transfer and evening walk through the UNESCO-listed fort." },
      { day: 2, title: "Galle & Unawatuna", description: "Heritage lanes, local markets and beach time." },
      { day: 3, title: "Mirissa", description: "Slow morning, coastal viewpoints and optional whale watching." },
      { day: 4, title: "To Yala", description: "Travel via fishing villages and the southern shoreline." },
      { day: 5, title: "Yala Safari", description: "Morning or evening private jeep safari with a naturalist." },
      { day: 6, title: "Onward Journey", description: "Transfer to Ella, Colombo or the airport." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
  {
    id: "demo-hills",
    title: "Tea Country Slow Journey",
    slug: "tea-country-slow-journey",
    location: "Kandy · Nuwara Eliya · Ella",
    durationDays: 4,
    priceFrom: 510,
    image: "https://images.unsplash.com/photo-1656314945066-edca54a983ec?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Misty tea estates, mountain roads, waterfalls and one of Asia's most beautiful train journeys.",
    description:
      "A relaxed highland escape built around tea culture, cooler weather and dramatic scenery. Enjoy local stories, scenic walks and flexible time in Ella.",
    highlights: ["Tea factory experience", "Hill-country train", "Nine Arch Bridge", "Waterfall stops"],
    inclusions: ["Private transfers", "Train ticket assistance", "Breakfast", "Driver-guide"],
    exclusions: ["Train tickets when sold separately", "Entrance fees", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Kandy to Nuwara Eliya", description: "Waterfalls, tea gardens and cool mountain scenery." },
      { day: 2, title: "Tea Country", description: "Factory visit, plantation walk and colonial town highlights." },
      { day: 3, title: "Scenic Train to Ella", description: "Classic rail journey through cloud forest and valleys." },
      { day: 4, title: "Ella Highlights", description: "Nine Arch Bridge, viewpoints and onward transfer." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
  {
    id: "demo-northern-explorer",
    title: "Northern Explorer",
    slug: "northern-explorer",
    location: "Anuradhapura · Jaffna",
    durationDays: 6,
    priceFrom: 780,
    image: "https://images.unsplash.com/photo-1546708973-e380fb144219?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Discover the untouched beauty, rich heritage, and unique culture of Sri Lanka's northern peninsula.",
    description:
      "Travel off the beaten path to explore ancient kingdoms and the vibrant Tamil culture of Jaffna. Enjoy quiet beaches, historic ruins, and spicy northern cuisine.",
    highlights: ["Jaffna Fort", "Nallur Kandaswamy Temple", "Anuradhapura ruins", "Casuarina Beach"],
    inclusions: ["Private transport", "Driver-guide", "Breakfast", "Temple entrance"],
    exclusions: ["Lunch and dinner", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Colombo to Anuradhapura", description: "Visit ancient stupas and the sacred Bodhi tree." },
      { day: 2, title: "To Jaffna", description: "Scenic drive north across the Elephant Pass." },
      { day: 3, title: "Jaffna Heritage", description: "Explore Jaffna Fort, library, and vibrant local markets." },
      { day: 4, title: "Islands & Temples", description: "Visit Nallur Temple and a nearby island via ferry." },
      { day: 5, title: "Return South", description: "Drive back towards the central province." },
      { day: 6, title: "Departure", description: "Transfer to airport or onward journey." },
    ],
    featured: false,
    status: "PUBLISHED",
  },
  {
    id: "demo-east-coast",
    title: "East Coast Paradise",
    slug: "east-coast-paradise",
    location: "Trincomalee · Passikudah",
    durationDays: 5,
    priceFrom: 650,
    image: "https://images.unsplash.com/photo-1596706938952-50b0cd0386ab?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Pristine white sand beaches, clear shallow waters, and vibrant marine life on the east coast.",
    description:
      "Escape to the tranquil east coast, featuring some of the island's best beaches. Perfect for sun seekers, snorkelers, and those looking to relax.",
    highlights: ["Pigeon Island snorkeling", "Koneswaram Temple", "Passikudah Bay", "Whale watching"],
    inclusions: ["Private transport", "Breakfast", "Snorkeling gear"],
    exclusions: ["National park fees", "Lunch and dinner"],
    itinerary: [
      { day: 1, title: "Airport to Trincomalee", description: "Cross the island to the east coast and relax." },
      { day: 2, title: "Trinco Highlights", description: "Visit Koneswaram Temple and relax at Nilaveli." },
      { day: 3, title: "Pigeon Island", description: "Morning boat ride for snorkeling with turtles and reef sharks." },
      { day: 4, title: "To Passikudah", description: "Short drive to calm, shallow waters for ultimate relaxation." },
      { day: 5, title: "Departure", description: "Transfer back to Colombo or airport." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
  {
    id: "demo-wildlife-nature",
    title: "Wildlife & Nature",
    slug: "wildlife-nature",
    location: "Sinharaja · Udawalawe",
    durationDays: 4,
    priceFrom: 550,
    image: "https://images.unsplash.com/photo-1620023606990-2e5bc004c2fb?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Immerse yourself in lush rainforests and observe herds of wild elephants in their natural habitat.",
    description:
      "A short but thrilling adventure focusing on Sri Lanka's incredible biodiversity. Trek through a UNESCO rainforest and enjoy an elephant safari.",
    highlights: ["Sinharaja Rainforest trek", "Udawalawe elephant safari", "Bird watching", "Eco-lodge stay"],
    inclusions: ["4WD safari jeep", "Trekking guide", "Breakfast", "Transport"],
    exclusions: ["Park entrance tickets", "Lunch and dinner"],
    itinerary: [
      { day: 1, title: "Colombo to Sinharaja", description: "Travel to the rainforest border and check into an eco-lodge." },
      { day: 2, title: "Rainforest Trekking", description: "Guided walk to spot endemic birds, reptiles, and flora." },
      { day: 3, title: "To Udawalawe", description: "Afternoon jeep safari to see elephant herds." },
      { day: 4, title: "Departure", description: "Morning visit to the Elephant Transit Home and onward travel." },
    ],
    featured: false,
    status: "PUBLISHED",
  },
  {
    id: "demo-ramayana-trail",
    title: "Ramayana Trail",
    slug: "ramayana-trail",
    location: "Colombo · Kandy · Nuwara Eliya",
    durationDays: 7,
    priceFrom: 850,
    image: "https://images.unsplash.com/photo-1583307613697-3c58253a6697?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Trace the mythological journey of the epic Ramayana through sacred temples and scenic highlands.",
    description:
      "A cultural and spiritual journey visiting key sites connected to the Ramayana epic. Explore beautiful temples and dramatic mountain landscapes.",
    highlights: ["Seetha Amman Temple", "Hakgala Botanical Garden", "Munneswaram Temple", "Ramboda Falls"],
    inclusions: ["Dedicated guide", "Private transport", "Daily breakfast"],
    exclusions: ["Site donations", "Lunch and dinner"],
    itinerary: [
      { day: 1, title: "Arrival & Chilaw", description: "Visit Munneswaram and Manavari Temples." },
      { day: 2, title: "To Kandy", description: "Travel to the hill capital and visit local shrines." },
      { day: 3, title: "Ramboda & Nuwara Eliya", description: "Visit Hanuman Temple and Ramboda Falls." },
      { day: 4, title: "Seetha Eliya", description: "Explore Seetha Amman Temple and Hakgala Gardens." },
      { day: 5, title: "Ella to Kataragama", description: "Visit the sacred multi-religious city of Kataragama." },
      { day: 6, title: "Galle to Colombo", description: "Coastal drive visiting Seenigama Temple." },
      { day: 7, title: "Departure", description: "Panchamuga Anjaneyar Temple in Colombo and airport drop." },
    ],
    featured: false,
    status: "PUBLISHED",
  },
  {
    id: "demo-surf-yoga",
    title: "Surf & Yoga Retreat",
    slug: "surf-yoga-retreat",
    location: "Arugam Bay",
    durationDays: 5,
    priceFrom: 600,
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Catch world-class waves and find inner peace with daily yoga in a laid-back surfer's paradise.",
    description:
      "The ultimate east coast vibe. Spend your days surfing famous point breaks, joining beachfront yoga sessions, and enjoying the vibrant cafe culture.",
    highlights: ["Surf lessons", "Daily yoga classes", "Lagoon safari", "Beachfront stay"],
    inclusions: ["Surfboard rental", "2 Yoga sessions", "Breakfast"],
    exclusions: ["Transport to Arugam Bay", "Lunch and dinner"],
    itinerary: [
      { day: 1, title: "Arrival in Arugam Bay", description: "Settle in and catch the sunset at Main Point." },
      { day: 2, title: "Surf & Stretch", description: "Morning surf lesson and evening yin yoga." },
      { day: 3, title: "Lagoon Safari", description: "Morning free time and afternoon boat safari to spot crocodiles." },
      { day: 4, title: "Explore Breaks", description: "Visit Whiskey Point or Peanut Farm for waves." },
      { day: 5, title: "Departure", description: "Final morning session before your onward journey." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
];

export const demoBikes: BikeDTO[] = [
  {
    id: "demo-dio",
    name: "Honda Dio 110",
    slug: "honda-dio-110",
    brand: "Honda",
    model: "Dio 110",
    engineCC: 110,
    category: "SCOOTER",
    dailyRateUSD: 12,
    depositUSD: 100,
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&w=1000&q=85",
    features: ["Helmet included", "Phone holder", "Under-seat storage", "Unlimited local support"],
    available: true,
    quantity: 5,
    status: "PUBLISHED",
  },
  {
    id: "demo-fz",
    name: "Yamaha FZ-S",
    slug: "yamaha-fz-s",
    brand: "Yamaha",
    model: "FZ-S",
    engineCC: 149,
    category: "MOTORBIKE",
    dailyRateUSD: 18,
    depositUSD: 150,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1000&q=85",
    features: ["Two helmets", "Phone holder", "Disc brake", "Roadside support"],
    available: true,
    quantity: 3,
    status: "PUBLISHED",
  },
  {
    id: "demo-xpulse",
    name: "Hero Xpulse 200",
    slug: "hero-xpulse-200",
    brand: "Hero",
    model: "Xpulse 200",
    engineCC: 199,
    category: "ADVENTURE",
    dailyRateUSD: 29,
    depositUSD: 250,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1000&q=85",
    features: ["Touring helmet", "USB charging", "Luggage rack", "Island-wide support"],
    available: true,
    quantity: 2,
    status: "PUBLISHED",
  },
  {
    id: "demo-himalayan",
    name: "Royal Enfield Himalayan",
    slug: "royal-enfield-himalayan",
    brand: "Royal Enfield",
    model: "Himalayan",
    engineCC: 411,
    category: "ADVENTURE",
    dailyRateUSD: 35,
    depositUSD: 300,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1558981420-c532902e58b4?auto=format&fit=crop&w=1000&q=85",
    features: ["Panniers", "Touring windscreen", "ABS", "24/7 Support"],
    available: true,
    quantity: 2,
    status: "PUBLISHED",
  },
  {
    id: "demo-crf250l",
    name: "Honda CRF250L",
    slug: "honda-crf250l",
    brand: "Honda",
    model: "CRF250L",
    engineCC: 250,
    category: "ADVENTURE",
    dailyRateUSD: 32,
    depositUSD: 250,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1599818815124-b33364f7b605?auto=format&fit=crop&w=1000&q=85",
    features: ["Off-road tires", "Hand guards", "Lightweight", "Helmet included"],
    available: true,
    quantity: 3,
    status: "PUBLISHED",
  },
  {
    id: "demo-ntorq",
    name: "TVS Ntorq 125",
    slug: "tvs-ntorq-125",
    brand: "TVS",
    model: "Ntorq",
    engineCC: 125,
    category: "SCOOTER",
    dailyRateUSD: 14,
    depositUSD: 100,
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1625477431109-c8cfcc193026?auto=format&fit=crop&w=1000&q=85",
    features: ["Bluetooth connectivity", "Digital console", "Under-seat storage", "City helmet"],
    available: true,
    quantity: 4,
    status: "PUBLISHED",
  },
  {
    id: "demo-pulsar200",
    name: "Bajaj Pulsar NS200",
    slug: "bajaj-pulsar-ns200",
    brand: "Bajaj",
    model: "Pulsar NS200",
    engineCC: 200,
    category: "MOTORBIKE",
    dailyRateUSD: 20,
    depositUSD: 150,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1599427301072-a0c3294c7b28?auto=format&fit=crop&w=1000&q=85",
    features: ["Liquid cooled", "Perimeter frame", "Disc brakes", "Phone mount"],
    available: true,
    quantity: 3,
    status: "PUBLISHED",
  },
  {
    id: "demo-mt15",
    name: "Yamaha MT-15",
    slug: "yamaha-mt-15",
    brand: "Yamaha",
    model: "MT-15",
    engineCC: 155,
    category: "MOTORBIKE",
    dailyRateUSD: 25,
    depositUSD: 200,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1601614059080-60b540f3b7db?auto=format&fit=crop&w=1000&q=85",
    features: ["Slipper clutch", "LED headlights", "Aggressive styling", "Premium helmets"],
    available: true,
    quantity: 2,
    status: "PUBLISHED",
  },
];

export const demoAirportVehicles: AirportVehicleDTO[] = [
  {
    id: "demo-budget-taxi",
    name: "Budget Taxi",
    slug: "budget-taxi",
    vehicleClass: "CAR",
    tier: "BUDGET",
    minPassengers: 1,
    maxPassengers: 3,
    luggagePieces: 2,
    priceFromUSD: 50,
    routePrices: demoRoutes({ Weligama: 50, Galle: 48, Kandy: 65, Ella: 105, Colombo: 28 }),
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A clean, air-conditioned taxi for light luggage and small groups.",
    features: ["Air-conditioned", "Meet and greet", "Flight tracking", "2 medium bags"],
    recommended: true,
    available: true,
    status: "PUBLISHED",
    sortOrder: 10,
  },
  {
    id: "demo-comfort-car",
    name: "Comfort Car",
    slug: "comfort-car",
    vehicleClass: "CAR",
    tier: "STANDARD",
    minPassengers: 1,
    maxPassengers: 3,
    luggagePieces: 3,
    priceFromUSD: 65,
    routePrices: demoRoutes({ Weligama: 65, Galle: 62, Kandy: 80, Ella: 125, Colombo: 35 }),
    image: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A private sedan with extra space, a cooler ride and a dedicated driver.",
    features: ["Private sedan", "Bottled water", "Name board pickup", "3 bags"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 20,
  },
  {
    id: "demo-luxury-sedan",
    name: "Luxury Sedan",
    slug: "luxury-sedan",
    vehicleClass: "CAR",
    tier: "LUXURY",
    minPassengers: 1,
    maxPassengers: 3,
    luggagePieces: 3,
    priceFromUSD: 95,
    routePrices: demoRoutes({ Weligama: 95, Galle: 90, Kandy: 115, Ella: 165, Colombo: 50 }),
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A premium car for a quieter, more polished arrival after a long flight.",
    features: ["Premium interior", "English-speaking chauffeur", "Refreshments", "Priority pickup"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 30,
  },
  {
    id: "demo-budget-van",
    name: "Budget Van",
    slug: "budget-van",
    vehicleClass: "VAN",
    tier: "BUDGET",
    minPassengers: 1,
    maxPassengers: 7,
    luggagePieces: 6,
    priceFromUSD: 75,
    routePrices: demoRoutes({ Weligama: 75, Galle: 72, Kandy: 95, Ella: 140, Colombo: 42 }),
    image: "https://images.unsplash.com/photo-1527786356703-4b32d19c0903?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A practical van when you need more seats and bags without a luxury fare.",
    features: ["Air-conditioned", "Room for families", "Surfboard-friendly", "6 bags"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 40,
  },
  {
    id: "demo-private-van",
    name: "Private Van",
    slug: "private-van",
    vehicleClass: "VAN",
    tier: "STANDARD",
    minPassengers: 1,
    maxPassengers: 7,
    luggagePieces: 7,
    priceFromUSD: 90,
    routePrices: demoRoutes({ Weligama: 90, Galle: 85, Kandy: 110, Ella: 155, Colombo: 48 }),
    image: "https://images.unsplash.com/photo-1464219782434-3473fb1918bc?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "The usual family choice — private, comfortable and ready for south-coast luggage.",
    features: ["High-roof van", "Child-seat on request", "Bottled water", "7 bags"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 50,
  },
  {
    id: "demo-luxury-van",
    name: "Luxury Van",
    slug: "luxury-van",
    vehicleClass: "VAN",
    tier: "LUXURY",
    minPassengers: 1,
    maxPassengers: 6,
    luggagePieces: 6,
    priceFromUSD: 130,
    routePrices: demoRoutes({ Weligama: 130, Galle: 125, Kandy: 155, Ella: 210, Colombo: 70 }),
    image: "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A refined van with extra comfort for families and small groups travelling together.",
    features: ["Leather seats", "Climate control", "Quiet cabin", "Chauffeur service"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 60,
  },
  {
    id: "demo-budget-minibus",
    name: "Budget Minibus",
    slug: "budget-minibus",
    vehicleClass: "MINIBUS",
    tier: "BUDGET",
    minPassengers: 8,
    maxPassengers: 14,
    luggagePieces: 12,
    priceFromUSD: 110,
    routePrices: demoRoutes({ Weligama: 110, Galle: 105, Kandy: 140, Ella: 190, Colombo: 65 }),
    image: "https://images.unsplash.com/photo-1544620341-11cb2cd07adc?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A straightforward group transfer when the priority is space and a fair price.",
    features: ["Group seating", "Large luggage hold", "Air-conditioned", "Driver included"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 70,
  },
  {
    id: "demo-standard-minibus",
    name: "Standard Minibus",
    slug: "standard-minibus",
    vehicleClass: "MINIBUS",
    tier: "STANDARD",
    minPassengers: 8,
    maxPassengers: 18,
    luggagePieces: 16,
    priceFromUSD: 140,
    routePrices: demoRoutes({ Weligama: 140, Galle: 135, Kandy: 170, Ella: 230, Colombo: 80 }),
    image: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "The reliable choice for larger groups heading to the coast, hills or city.",
    features: ["Up to 18 seats", "Meet and greet", "Flight tracking", "Generous luggage"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 80,
  },
  {
    id: "demo-luxury-coach",
    name: "Luxury Coach",
    slug: "luxury-coach",
    vehicleClass: "MINIBUS",
    tier: "LUXURY",
    minPassengers: 8,
    maxPassengers: 15,
    luggagePieces: 15,
    priceFromUSD: 190,
    routePrices: demoRoutes({ Weligama: 190, Galle: 180, Kandy: 230, Ella: 290, Colombo: 110 }),
    image: "https://images.unsplash.com/photo-1570125909517-53cb21c89ff2?auto=format&fit=crop&w=1200&q=80",
    shortDescription: "A premium coach for groups who want more comfort on longer island transfers.",
    features: ["Reclining seats", "USB charging", "Professional chauffeur", "Quiet cabin"],
    recommended: false,
    available: true,
    status: "PUBLISHED",
    sortOrder: 90,
  },
];
