import type { BikeDTO, TourDTO } from "@/types";

export const demoTours: TourDTO[] = [
  {
    id: "demo-cultural-triangle",
    title: "Ceylon Cultural Triangle",
    slug: "ceylon-cultural-triangle",
    location: "Sigiriya · Dambulla · Kandy",
    durationDays: 5,
    priceFrom: 620,
    image: "https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Ancient kingdoms, cave temples, village flavours and sunrise views across the heart of Sri Lanka.",
    description:
      "Follow the story of Sri Lanka through its ancient capitals, sacred temples and living village traditions. This private journey balances meaningful cultural encounters with comfortable travel and flexible stops.",
    highlights: [
      "Climb Sigiriya Rock Fortress",
      "Traditional village lunch",
      "Dambulla cave temple",
      "Kandy cultural performance",
    ],
    inclusions: ["Private air-conditioned transport", "English-speaking driver", "Daily breakfast", "Airport pickup"],
    exclusions: ["International flights", "Entrance tickets", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Airport to Sigiriya", description: "Welcome at Bandaranaike International Airport and scenic transfer to the cultural triangle." },
      { day: 2, title: "Sigiriya & Village Life", description: "Sunrise rock climb, village walk, local cooking and a relaxed afternoon." },
      { day: 3, title: "Dambulla to Kandy", description: "Visit the cave temple, spice gardens and continue through the hills to Kandy." },
      { day: 4, title: "Sacred Kandy", description: "Temple of the Tooth, botanical gardens and a traditional cultural performance." },
      { day: 5, title: "Departure", description: "Flexible transfer to Colombo, the airport or your next destination." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
  {
    id: "demo-coast",
    title: "Southern Coast & Safari",
    slug: "southern-coast-and-safari",
    location: "Galle · Mirissa · Yala",
    durationDays: 6,
    priceFrom: 740,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Fort walls, golden beaches, ocean adventures and a private wildlife safari through the island's south.",
    description:
      "Experience the easy rhythm of Sri Lanka's south coast before heading inland for a wildlife safari. The route includes heritage, local food, beach time and optional whale watching.",
    highlights: ["Galle Fort sunset", "Mirissa beach stay", "Yala jeep safari", "Stilt fishing coast"],
    inclusions: ["Private transport", "Driver-guide", "Breakfast", "Safari jeep"],
    exclusions: ["Park tickets", "Whale watching ticket", "Lunch and dinner"],
    itinerary: [
      { day: 1, title: "Airport to Galle", description: "Coastal transfer and evening walk through the UNESCO-listed fort." },
      { day: 2, title: "Galle & Unawatuna", description: "Heritage lanes, local markets and beach time." },
      { day: 3, title: "Mirissa", description: "Slow morning, coastal viewpoints and optional whale watching." },
      { day: 4, title: "To Yala", description: "Travel via fishing villages and the southern shoreline." },
      { day: 5, title: "Yala Safari", description: "Morning or evening private jeep safari with a naturalist." },
      { day: 6, title: "Onward Journey", description: "Transfer to Ella, Colombo or the airport." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
  {
    id: "demo-hills",
    title: "Tea Country Slow Journey",
    slug: "tea-country-slow-journey",
    location: "Kandy · Nuwara Eliya · Ella",
    durationDays: 4,
    priceFrom: 510,
    image: "https://images.unsplash.com/photo-1656314945066-edca54a983ec?auto=format&fit=crop&w=1200&q=85",
    shortDescription:
      "Misty tea estates, mountain roads, waterfalls and one of Asia's most beautiful train journeys.",
    description:
      "A relaxed highland escape built around tea culture, cooler weather and dramatic scenery. Enjoy local stories, scenic walks and flexible time in Ella.",
    highlights: ["Tea factory experience", "Hill-country train", "Nine Arch Bridge", "Waterfall stops"],
    inclusions: ["Private transfers", "Train ticket assistance", "Breakfast", "Driver-guide"],
    exclusions: ["Train tickets when sold separately", "Entrance fees", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Kandy to Nuwara Eliya", description: "Waterfalls, tea gardens and cool mountain scenery." },
      { day: 2, title: "Tea Country", description: "Factory visit, plantation walk and colonial town highlights." },
      { day: 3, title: "Scenic Train to Ella", description: "Classic rail journey through cloud forest and valleys." },
      { day: 4, title: "Ella Highlights", description: "Nine Arch Bridge, viewpoints and onward transfer." },
    ],
    featured: true,
    status: "PUBLISHED",
  },
];

export const demoBikes: BikeDTO[] = [
  {
    id: "demo-dio",
    name: "Honda Dio 110",
    slug: "honda-dio-110",
    brand: "Honda",
    model: "Dio 110",
    engineCC: 110,
    category: "SCOOTER",
    dailyRateUSD: 12,
    depositUSD: 100,
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1591637333184-19aa84b3e01f?auto=format&fit=crop&w=1000&q=85",
    features: ["Helmet included", "Phone holder", "Under-seat storage", "Unlimited local support"],
    available: true,
    quantity: 5,
    status: "PUBLISHED",
  },
  {
    id: "demo-fz",
    name: "Yamaha FZ-S",
    slug: "yamaha-fz-s",
    brand: "Yamaha",
    model: "FZ-S",
    engineCC: 149,
    category: "MOTORBIKE",
    dailyRateUSD: 18,
    depositUSD: 150,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1000&q=85",
    features: ["Two helmets", "Phone holder", "Disc brake", "Roadside support"],
    available: true,
    quantity: 3,
    status: "PUBLISHED",
  },
  {
    id: "demo-xpulse",
    name: "Hero Xpulse 200",
    slug: "hero-xpulse-200",
    brand: "Hero",
    model: "Xpulse 200",
    engineCC: 199,
    category: "ADVENTURE",
    dailyRateUSD: 29,
    depositUSD: 250,
    transmission: "MANUAL",
    fuelType: "PETROL",
    seats: 2,
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1000&q=85",
    features: ["Touring helmet", "USB charging", "Luggage rack", "Island-wide support"],
    available: true,
    quantity: 2,
    status: "PUBLISHED",
  },
];
